### ISSUE TITLE
Kudos comment field - cursor jumps to end

### ISSUE THREAD

**Issue by davidatada** [mathsian/dashboard#65]
When editing in the kudos form "comment" field, the cursor will jump to the end of the text after any character is entered meaning making an edit in the middle of an existing comment is difficult.

**Comment by mathsian** [comment]
Confirmed. This seems to affect both the kudos comment field and the concern description. I think it's an example of #[this bug](https://github.com/facultyai/dash-bootstrap-components/issues/694) in the underlying component. If that one isn't fixed by the next dashboard version we'll revert to the input component in `dash_core_components`.

**Comment by tcbegley** [comment]
Hi, sorry this bug crept in. I've made a patch release of dash-bootstrap-components which should fix it, and it should also be fixed in the latest beta of version 1.

Do raise an issue on the dash-bootstrap-components repo if you still have problems!

**Comment by mathsian** [comment]
Thanks @tcbegley. Working well now.
